### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by panjj95** [HJH201314/ChainMiner#11]
[minidump_2024-07-08_16-54-41.zip](https://github.com/user-attachments/files/16250590/minidump_2024-07-08_16-54-41.zip)
![Screenshot_20240716_223707](https://github.com/user-attachments/assets/9d811bca-e1d0-4f24-af64-4ea1709a706d)

**Comment by HJH201314** [comment]
ChainMiner3 可反馈至 https://github.com/engsr6982/ChainMiner3/issues
