### ISSUE TITLE
和假矿插件冲突

### ISSUE THREAD

**Issue by jfishing** [HJH201314/ChainMiner#3]
首先感谢作者的辛苦付出！假矿插件是在一个矿方块破坏后，改变其周围的方块，所以链锁挖掉的可能并不是该种矿。可否改变链锁逻辑，变成一个矿方块破坏后再识别周围六个面的方块进行连锁破坏，以此来适配假矿插件。望作者考虑，谢谢。

**Comment by HJH201314** [comment]
我有空看看:D

**Comment by HJH201314** [comment]
好的

**Comment by HJH201314** [comment]
Fixed in [402c1581e08c63423afce272579d39aa0882c502](https://github.com/HJH201314/ChainMiner/commit/402c1581e08c63423afce272579d39aa0882c502)
