### ISSUE TITLE
求更新了

### ISSUE THREAD

**Issue by panjj95** [HJH201314/ChainMiner#5]
ll2.11.0， bds1.19.63，别人领地内挖掘崩了

**Comment by panjj95** [comment]
![Uploading Screenshot_20230311_142500_com.huawei.browser.jpg…]()

**Comment by HJH201314** [comment]
太忙了。。。刚刚打算更新编译一下，然后LLAPI那边不知道又在乱改什么，没法通过编译。。。麻烦死了
