### ISSUE TITLE
催更1.19.80

### ISSUE THREAD

**Issue by panjj95** [HJH201314/ChainMiner#7]
催更1.19.80，辛苦了😅

**Comment by HJH201314** [comment]
2.13刚发，先别急😶‍🌫️

**Comment by panjj95** [comment]
可以更新了😭

**Comment by HJH201314** [comment]
1.19.80有一点改动，在搞了

**Comment by HJH201314** [comment]
Updated [af99ced](https://github.com/HJH201314/ChainMiner/commit/af99cedcdd58fcef67015d5bacaffffdc531998b)
